[project]
name = "pdf-book-split"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "fitz>=0.0.1.dev2",
    "pymupdf>=1.25.5",
]
